### ISSUE TITLE
Suddenly the bot does not send pictures

### ISSUE THREAD

**Issue by aguilard07** [art-vasilyev/instachatbot#15] opened 2019-10-15 21:51 UTC
Hi, I've using this bot for while but when I started it this afternoon, when a picture is requested, this error appears:
`ERROR:instabot:Request returns 400 error!`

The code I've been using is the same that weeks ago that worked perfectly sending .jpg files.

My version of instabot is 0.4.2 and instachatbot is 0.3.2
I also tried upgrading instabot to 0.6.9 but with not success login in.

**Comment by art-vasilyev** [comment] 2019-10-16 10:03
Hi, looks like this is caused by changes in instagram API, please submit an issue in the [instabot](https://github.com/instagrambot/instabot) repository. You can check picture uploading by this example script: https://github.com/instagrambot/instabot/blob/master/examples/direct_send_photo.py

**Comment by aguilard07** [comment] 2019-10-16 10:35
I thought so, but Instabot is right now in version 0.6.9 and your framework works with 0.42. Is in your plans to upload it?

**Comment by art-vasilyev** [comment] 2019-10-16 10:46
I reproduced this error in latest version of instabot. I have plans to upgrade instabot version, but don't have enough time for that. Pull requests are welcome, there are not much changes needed for upgrade

**Comment by art-vasilyev** [comment] 2019-12-04 20:00
closing issue cause it's relates with instabot framework

**Closed by art-vasilyev** 2019-12-04 20:00 UTC
